--:help options
local options = {
	autoindent = true,
	autowrite  = true,
	background = 'dark',
	backspace = {'start', 'eol', 'indent'},
	backup = false,
	breakindent = true,
	clipboard = {'unnamed', 'unnamedplus'},
	completeopt = {'menu', 'menuone', 'noselect'},
	confirm = true,
	encoding = 'utf-8',
	errorbells = false,
	fileencoding = 'utf-8',
	guifont = 'JetBrainsMonoNL Nerd Font:h10',
	hidden = true,
	hlsearch = true,
	ignorecase = true,
	inccommand = 'split',
	incsearch = true,
	laststatus = 2,
	linebreak = true,
	mouse = 'a',
	number = true,
	relativenumber = false,
	ruler = false,
	scrolloff = 8,
	shell = 'zsh',
	shiftround = true,
	shiftwidth = 2,
	showmatch = true,
	sidescrolloff = 15,
	signcolumn = 'yes',
	smartcase = true,
	smarttab = true,
	splitbelow = true,
	splitright = true,
	swapfile = false,
	tabstop = 2,
	termguicolors = true,
	timeoutlen = 1000,
	title = true,
	undofile = true,
	updatetime = 100,
	visualbell = true,
	wildmenu = true,
	wrap = false,
	writebackup = false,
}

vim.opt.shortmess:append "c"
vim.opt.whichwrap:append "<,>,[,],h,l"

for k, v in pairs(options) do
	vim.opt[k] = v
end
