return {
	"lukas-reineke/indent-blankline.nvim",
	opts = {
		char = "¦",
		show_trailing_blankline_indent = false,
		show_current_context = true,
		show_first_indent_level = true,
		filetype_exclude = {
			'packer',
			'markdown',
			'help',
			'TelescopePrompt',
			'Trouble',
			'yaml',
			'',
		},
		buftype_exclude = { 'terminal', 'nofile' },
		context_patterns = {
			'^for',
			'^if',
			'^object',
			'^table',
			'^while',
			'argument_list',
			'arguments',
			'block',
			'bracket',
			'class',
			'declaration',
			'dictionary',
			'element',
			'except',
			'expression',
			'from',
			'func_literal',
			'function',
			'list',
			'method',
			'pattern',
			'primary_expression',
			'set',
			'statement',
			'switch_body',
			'try',
			'tuple',
			'with',
		},
	}
}
